import type { Entry } from "./types";

export const work: Entry[] = [
  {
    icon: "apple",
    title: "Apple",
    subheader: "Software Engineer",
    tier: "primary",
    accent: "rgb(51, 51, 51)",
    platforms: ["iOS", "iPadOS", "visionOS", "macOS"],
    languages: ["Swift", "SwiftUI", "Objective-C", "C++"],
    link: "https://apple.com/",
    location: "Cupertino, California",
    dates: [{ start: "May 2024", end: "Aug 2024" }, { start: "May 2025", end: "Dec 2025" }, { start: "May 2026", end: "Aug 2026" }],
  },
  {
    icon: "stealth",
    title: "Stealth",
    subheader: "Founding Engineer",
    tier: "legacy",
    accent: "#7c8aa8",
    description:
      "Founding engineer at a stealth AI startup. Built the product end-to-end across agentic systems, native apps, web, backend, and developer SDKs. Architected the production stack: agent swarms, persistent state, real-time event delivery, and isolated execution sandboxes. Designed the core primitives powering autonomous agents: scheduling, cost governance, approval workflows, persistent memory, and tool integration.",
    platforms: ["Web", "Cloud", "iOS", "macOS"],
    languages: ["TypeScript", "Python", "Swift", "Rust"],
    location: "Remote",
    dates: [{ start: "Jan 2026", end: "April 2026" }],
  },
  {
    icon: "exa",
    title: "Exa.ai",
    subheader: "Member of Technical Staff",
    tier: "primary",
    accent: "rgb(19, 52, 200)",
    description:
      "Built Exa's /answer endpoint, the **first RAG system to clear 90%+ on SimpleQA, beating OpenAI**, Perplexity, and DeepSeek. Engineered crawling infrastructure indexing billions of URLs. Led fullstack on Exa Websets, a platform for AI-driven sourcing and verification. Drove **multi-million-dollar** enterprise deals.",
    link: "https://exa.ai/",
    platforms: ["Web", "Cloud"],
    languages: ["Python", "TypeScript", "Rust"],
    location: "San Francisco, California",
    dates: [{ start: "Oct 2024", end: "Apr 2025" }, { start: "Aug 2026" }],
  },
  {
    icon: "snowflake",
    title: "Snowflake",
    subheader: "Software Engineer Intern",
    tier: "primary",
    accent: "#00A1D9",
    description:
      "**Youngest engineering intern** at Snowflake. **Founding engineer on Snowflake Notebooks**, the company's ML and data-analysis platform, building client and server infrastructure used across ML, Data Marketplace, Modeling, and Query teams.",
    platforms: ["Web", "Cloud"],
    languages: ["TypeScript", "Golang", "Node.js", "Python", "SQL"],
    link: "https://www.snowflake.com/",
    location: "San Mateo, CA",
    dates: [{ start: "Jun 2023", end: "Dec 2023" }],
  },
  {
    icon: "neeva",
    title: "Neeva",
    subheader: "Software Engineer",
    tier: "primary",
    accent: "rgb(68, 85, 238)",
    accentSoft: "rgb(116, 176, 235)",
    description:
      "Core engineer on the **world's first generative-AI search application**. Led iOS development on the Neeva browser, shipping to the App Store with **1,000+ five-star reviews**.",
    platforms: ["iOS", "iPadOS", "macOS", "Web", "Android"],
    languages: ["Swift", "SwiftUI", "Combine", "Kotlin", "TypeScript"],
    location: "Mountain View, CA",
    dates: [{ start: "May 2021", end: "May 2023" }],
  },
  {
    icon: "ferdasoft",
    title: "Ferdasoft",
    subheader: "Founder & Head of Engineering",
    tier: "legacy",
    accent: "rgb(32, 39, 83)",
    description:
      "Founded and led Ferdasoft, building **Nome - Music & Maps** for iOS, WatchOS, CarPlay, and Web. **Featured by Apple** in 'Our Favorites' and 'Hot New Apps', with coverage from Product Hunt and iMore.",
    platforms: ["iOS", "WatchOS", "Apple CarPlay", "Web"],
    languages: ["Swift", "SwiftUI", "UIKit", "JavaScript"],
    location: "Portland, Oregon",
    dates: [{ start: "Mar 2020", end: "May 2023" }],
  },
  {
    icon: "trivory",
    title: "Trivory",
    subheader: "Software Engineer & Designer",
    tier: "legacy",
    accent: "rgb(78, 171, 121)",
    description:
      "Designed and shipped Apple-platform applications for **20,000+ users** across Portland Public Schools.",
    platforms: ["iOS"],
    languages: ["Swift", "SwiftUI", "Apache Cordova"],
    link: "https://trivory.com",
    location: "Portland, Oregon",
    dates: [{ start: "2022", end: "2023" }],
  },
  {
    icon: "travsolo",
    title: "TravSolo",
    subheader: "Co-Founder & Head of Engineering",
    tier: "legacy",
    accent: "rgb(85, 169, 221)",
    description:
      "Co-founder and head of engineering. Led app development and shipped revenue-generating features. Partnered with the CEO to **raise $100k+** in capital.",
    platforms: ["iOS"],
    languages: ["Swift", "UIKit"],
    link: "https://travsolo.com",
    location: "Portland, Oregon",
    dates: [{ start: "May 2021", end: "Sept 2021" }],
  },
];
